CarlitosWP/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Carlos_Home.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Carlos_Home/urls.py
from django.conf.urls import url
from .views import home, about, ContactView, Registros, Reportes, CursoView, ProfesionitaView, admin, PacienteView, ReporteProfesionista, ReportePaciente, ReporteCurso, Crear_Post, post_detalle, post_lista, Crear_Categoria, BlogAdmin, Registro, Cursos, test, Blog

urlpatterns = [
	url(r'^$', 'django.contrib.auth.views.login', {'template_name': 'Carlos_Home/home.html'}, name='login'),
	url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^$', home, name= "home"),
    url(r'^about/$',about, name = "about_view"),
    url(r'^contacto$', ContactView.as_view(), name = "contacto"),
    url(r'^registros$', Registros, name = "registros_view"),
    url(r'^reportes$', Reportes, name = "reportes_view"),
    url(r'^registro_curso$', CursoView.as_view(), name = "CursoView_view" ),
    url(r'^registro_profesionista$',ProfesionitaView.as_view(), name = "ProfesionitaView_view"),
    url(r'^panel_admin$', admin, name = "admin_panel"),
    url(r'^registro_paciente$', PacienteView.as_view(), name = "PacienteView_view"),
    url(r'^ReporteProfesionista/$', ReporteProfesionista.as_view(), name='reporte_profesionista_view'),
	url(r'^ReportePaciente/$', ReportePaciente.as_view(), name='reporte_paciente_view'),
    url(r'^ReporteCurso/$', ReporteCurso.as_view(), name='reporte_curso_view'),
    url(r'^Crear_Post/$', Crear_Post.as_view(), name='crear_post_view'),
    url(r'^post_detalle/(?P<id>\d+)/$', post_detalle, name='post_detalle'),
    url(r'^post_lista/$', post_lista, name='post_lista'),
    url(r'^Crear_Categoria/$', Crear_Categoria.as_view(), name='crear_categoria_view'),
    url(r'^blogadmin/$', BlogAdmin, name= "blog_admin"),
    url(r'^registro/$', Registro.as_view(), name='registro_view'),
	url(r'^cursos/$', Cursos, name = "cursos_view"),
	url(r'^test/$', test, name = "test_view"),
	url(r'^blog/$', Blog.as_view(), name = 'blog' )
]

Carlos_Home/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Cursos(models.Model):
    numero_curso = models.IntegerField(unique=True)
    curso = models.CharField(max_length=50)

    def __str__(self):
        return self.curso

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    orden = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

class Post(models.Model):
        titulo = models.CharField(max_length = 200)
        contenido = models.TextField()
        slug = models.SlugField(unique=True)
        categorias = models.ForeignKey(Categoria)
        post_imagen = models.ImageField(upload_to='post_imagen/')
        creado = models.DateTimeField(default=timezone.now)
        post_video = models.CharField(max_length = 300, null = True)

        def __str__(self):
            return self.titulo

class Profesionista(models.Model):
    perfil_usuario = models.OneToOneField(User)
    nombre_profesionista = models.CharField(max_length = 68)
    apellido_profesionista = models.CharField(max_length = 68)
    reportes = models.CharField(max_length = 2)
    horario = models.CharField(max_length=50)
    telefono = models.IntegerField()
    curso = models.ForeignKey(Cursos)
    email = models.EmailField()

    def __unicode__(self):
        return(self.curso)

    def __str__(self):
        return 'nombre: %s - curso: %s' %(self.nombre_profesionista, self.curso)

class Paciente(models.Model):
    perfil_usuario = models.OneToOneField(User)
    nombre_paciente = models.CharField(max_length = 99)
    apellido_paciente = models.CharField(max_length = 99)
    num_expediente = models.IntegerField()
    area = models.CharField(max_length = 30)
    fecha_ingreso = models.DateField(default=timezone.now)
    fecha_conclusion = models.DateField(default=timezone.now)
    evaluacion_completa = models.CharField(max_length = 2)
    reportes = models.CharField(max_length = 2)
    diagnostico = models.CharField(max_length = 45)
    fecha_nacimiento = models.DateField(default=timezone.now)
    edad_ingreso = models.IntegerField()
    telefono = models.IntegerField()
    email = models.EmailField()
    genero = models.CharField(max_length=1)


    def __str__(self):
        return 'nombre: %s - numero expediente: %d - edad ingreso: %d' %(self.nombre_paciente, num_expediente, edad_ingreso)

class Perfil(models.Model):
	perfil_usuario = models.OneToOneField(User)
	email = models.EmailField()

Carlos_Home/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Cursos, Categoria

class ContactForm(forms.Form):
    name = forms.CharField()
    emal = forms.CharField();
    message = forms.CharField(widget = forms.Textarea)

    def send_email(self):
        pass

class RegistroCursoForm(forms.Form):
    numero_curso = forms.IntegerField()
    curso = forms.CharField(max_length=50)

class ProfesionistaForm(UserCreationForm):
    reportes = forms.CharField()
    HORARIO = (
                    ('M', 'Matutino'),
                    ('V', 'Vespertino'),
                )
    horario = forms.ChoiceField(choices = HORARIO)
    telefono = forms.IntegerField()
    curso = forms.ModelChoiceField(Cursos.objects.values_list('curso'), empty_label= "Selecciona Curso")
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')


class PacienteForm(UserCreationForm):
    num_expediente = forms.IntegerField()
    area = forms.CharField()
    fecha_ingreso = forms.DateField(input_formats = ['%m/%d/%y'])
    fecha_conclusion = forms.DateField(input_formats = ['%m/%d/%y'])
    evaluacion_completa = forms.CharField()
    reportes = forms.CharField()
    diagnostico = forms.CharField()
    fecha_nacimiento = forms.DateField(input_formats = ['%m/%d/%y'])
    edad_ingreso = forms.IntegerField()
    telefono = forms.IntegerField()
    email = forms.EmailField()
    ELECCION_GENERO = (
                    ('M', 'Masculino'),
                    ('F', 'Femenino'),
                    )
    genero = forms.ChoiceField(choices=ELECCION_GENERO)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

class User_form(UserCreationForm):
	email = forms.CharField(max_length=99)

class PostForm(forms.Form):
    titulo = forms.CharField()
    contenido = forms.CharField(widget=forms.Textarea)
    slug = forms.SlugField()
    categorias = forms.ModelChoiceField(Categoria.objects.values_list('nombre'),  empty_label= "Selecciona Categoria")
    post_imagen = forms.ImageField()
    creado = forms.DateTimeField(input_formats = ['%m/%d/%Y %H:%M:%S'])
    post_video = forms.CharField()

Carlos_Home/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.views.generic import TemplateView, FormView, CreateView, ListView, UpdateView, DetailView
from .forms import  ContactForm, RegistroCursoForm, ProfesionistaForm, PacienteForm, User_form, PostForm
from django.core.urlresolvers import reverse_lazy
from .models import Cursos, Profesionista, Paciente, Post, Categoria
from django.core.mail import send_mail
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def home(request):
    queryset_list = Post.objects.all().order_by('creado')
    paginator = Paginator(queryset_list, 3) # Show 3 contacts per page

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
		# If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
        context = {
		"object_list": queryset
	       }
    return render(request, 'Carlos_Home/home.html', context)

def about(request):
    return render(request, 'Carlos_Home/about.html')

class ContactView(FormView):
    template_name = 'Carlos_Home/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form_email = form.cleaned_data.get('emal')
        form_message = form.cleaned_data.get('message')
        form_name = form.cleaned_data.get('name')

        subject = 'Test Mailbox'
        contact_message ='%s: %s Via: %s'%(form_name,form_message,form_email)
        from_email = settings.EMAIL_HOST_USER
        to_email =[from_email]
        send_mail(subject, contact_message, from_email,to_email, fail_silently=False)
        return super(ContactView, self).form_valid(form)



def Registros(request):
    return render(request, 'Carlos_Home/Registros.html')

def Reportes(request):
    return render(request, 'Carlos_Home/Reportes.html')

class CursoView(FormView):
    template_name = 'Carlos_Home/Registro_curso.html'
    form_class = RegistroCursoForm
    success_url = reverse_lazy('registros_view')

    def form_valid(self, form):
        p = Cursos()
        p.numero_curso = form.cleaned_data['numero_curso']
        p.curso = form.cleaned_data['curso']
        p.save()
        return super(CursoView,self).form_valid(form)

class ProfesionitaView(FormView):
    template_name = 'Carlos_Home/Registro_prof.html'
    form_class = ProfesionistaForm
    success_url = reverse_lazy('registros_view')

    def form_valid(self,form):
        user = form.save()
        p = Profesionista()
        p.perfil_usuario = user
        p.nombre_profesionista = user.first_name
        p.apellido_profesionista = user.last_name
        p.reportes = form.cleaned_data['reportes']
        p.horario = form.cleaned_data['horario']
        p.telefono = form.cleaned_data['telefono']
        p.curso = form.cleaned_data['curso']
        p.email = form.cleaned_data['email']
        p.save()
        return super(ProfesionitaView,self).form_valid(form)

def admin(request):
    return render(request, 'Carlos_Home/Admin.html')

class PacienteView(FormView):
    template_name = 'Carlos_Home/Registro_paciente.html'
    form_class = PacienteForm
    success_url = reverse_lazy('registros_view')

    def form_valid(self,form):
        user = form.save()
        p = Paciente()
        p.perfil_usuario = user
        p.nombre_paciente = user.first_name
        p.apellido_paciente = user.last_name
        p.num_expediente = form.cleaned_data['num_expediente']
        p.area = form.cleaned_data['area']
        p.fecha_ingreso = form.cleaned_data['fecha_ingreso']
        p.fecha_conclusion = form.cleaned_data['fecha_conclusion']
        p.evaluacion_completa = form.cleaned_data['evaluacion_completa']
        p.reportes = form.cleaned_data['reportes']
        p.diagnostico = form.cleaned_data['diagnostico']
        p.fecha_nacimiento = form.cleaned_data['fecha_nacimiento']
        p.edad_ingreso = form.cleaned_data['edad_ingreso']
        p.telefono = form.cleaned_data['telefono']
        p.email = form.cleaned_data['email']
        p.genero = form.cleaned_data['genero']
        p.save()
        return super(PacienteView,self).form_valid(form)

class ReportePaciente(ListView):
	template_name = 'Carlos_Home/reporte_paciente.html'
	model = Paciente
	fields = '__all__'

class ReporteProfesionista(ListView):
	template_name = 'Carlos_Home/reporte_profesionista.html'
	model = Profesionista
	fields = '__all__'

class ReporteCurso(ListView):
	template_name = 'Carlos_Home/reporte_cursos.html'
	model = Cursos
	fields = '__all__'

class Crear_Categoria(CreateView):
    template_name='Carlos_Home/CrearCategoria.html'
    model = Categoria
    fields= '__all__'
    success_url=reverse_lazy('index_view')

def post_detalle(request, id=None):
	post = get_object_or_404(Post, id=id)
	context = {
		"object_list": "eee",
		"post": post,
	}
	return render(request, "Carlos_Home/post_detalle.html", context)

def post_lista(request):
	queryset_list = Post.objects.all().order_by('-creado')
	paginator = Paginator(queryset_list, 3) # Show 3 contacts per page

	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset
	}
	return render(request, "Carlos_Home/post_lista.html", context)

def BlogAdmin(request):
    return render(request, "Carlos_Home/blogadmin.html")

class Registro(FormView):
	template_name = 'Carlos_Home/registro.html'
	form_class = User_form
	#fields = ['user_perfil', 'mail', 'phone']
	success_url = reverse_lazy('signup_view')


	def form_valid(self, form):
		user = form.save()
		p = Perfil()
		p.perfil_usuario = user
		p.mail = form.cleaned_data['email']
		p.save()
		return super(Signup, self).form_valid(form)

class Crear_Post(FormView):
    template_name = 'Carlos_Home/CrearPost.html'
    form_class = PostForm
    success_url=reverse_lazy('index_view')

    def form_valid(self,form):
        p = Post()
        p.titulo = form.cleaned_data['titulo']
        p.contenido = form.cleaned_data['contenido']
        p.slug = form.cleaned_data['slug']
        p.categorias = form.cleaned_data['categorias']
        p.post_imagen = form.cleaned_data['post_imagen']
        p.creado = form.cleaned_data['creado']
        p.post_video = form.cleaned_data['post_video']
        p.save()
        return super(Crear_Post, self).form_valid(form)

def Cursos(request):
    return render(request, "Carlos_Home/cursos.html")

def test(request):
    return render (request, "Carlos_Home/test.html")

class Blog(ListView):
    template_name = 'Carlos_Home/blog.html'
    model = Post
    fields = '__all__'

Carlos_Home/templates/Carlos_Home/Admin.html
{% extends 'base.html' %}
{% block title %}Administracion {% endblock %}
{% block inicio %}
<li class="active"><a href="{% url 'home' %}" data-nav-section="home"><span>Inicio</span></a></li>
{% endblock %}
{% block content %}
<aside class="callout">
  <div class="text-vertical-center">
      <h1 style="color: #fff">Panel de Control</h1>
  </div>
</aside>
<div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>Opciones</h2>
                <hr class="small">
                <div  class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span style = "color: #0000ff" class="fa-stack fa-4x">
                              <i class="fa fa-circle fa-stack-2x"></i>
                              <i style = "color: #fff" class="fa fa-pencil-square-o fa-stack-1x text-primary"></i>
                            </span>
                            <h4>
                                <strong>Blog</strong>
                            </h4>
                            <p>For new users </p>
                            <a href="{% url 'blog_admin' %}"  class="btn btn-primary btn-lg">Click Here!</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span style = "color: #00e600" class="fa-stack fa-4x">
                              <i class="fa fa-circle fa-stack-2x"></i>
                              <i style = "color: #fff" class="fa fa-file-text fa-stack-1x text-primary"></i>
                            </span>
                            <h4>
                                <strong>Edicion Registros</strong>
                            </h4>
                            <p>Start a new order</p>
                            <a href="#"  class="btn btn-primary btn-lg">Click Here!</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span style = "color: #e6e600" class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i style = "color: #fff" class="fa fa-newspaper-o fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Reportes</strong>
                            </h4>
                            <p>Quality Options for Supervisors</p>
                            <a href="{% url 'CursoView_view' %}"  class="btn btn-primary btn-lg">Click Here!</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span style = "color: #ff0000" class="fa-stack fa-4x">
                            <i  class="fa fa-circle fa-stack-2x"></i>
                            <i style = "color: #fff" class="fa fa-file-text fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Otro</strong>
                            </h4>
                            <p>Report Seccction for the Bauss</p>
                            <a href="#"  class="btn btn-primary btn-lg">Click Here!</a>
                        </div>
                    </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
  </div>
    <!-- /.container -->

{% endblock %}

Carlos_Home/templates/Carlos_Home/CrearCategoria.html
{% extends "base.html" %}

{% block title %}Create Category{% endblock %}
{% block header %}
	<h1>Create Category</h1>
{% endblock %}
{% block content %}
<h1 style="text-align: center;"> Create Category </h1>
{% if user.is_authenticated %}
{% if user.is_superuser %}
Binevenido {{ user.username }}<br>

		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="enviar">
		</form>
{% endif %}
{% endif %}

{% endblock %}

Carlos_Home/templates/Carlos_Home/Registro_paciente.html
{% extends 'base.html' %}
{% block title %}Registrar Paciente {% endblock %}
{% block inicio %}
<li class="active"><a href="{% url 'home' %}" data-nav-section="home"><span>Inicio</span></a></li>
{% endblock %}
{% block content %}
<aside class="callout">
  <div class="text-vertical-center">
      <h1 style="color: #fff">Registro Paciente</h1>
  </div>
</aside>
{% if form.errors %}
<h3>Error</h3>
{{ form.errors }}
{% endif %}
<div class="row">
  <form role = "form" method="POST">
    {% csrf_token %}
    <div class="container text-center" style="padding-top: 15px;">
      <h2>Completa el formulario</h2>
      <hr style="padding-bottom: 15px;" class="small">
      <div class="col-sm-8 col-sm-offset-2">
      <div class="form-group float-label-control">
        <label for="id_username">Username:</label> <input id="id_username" maxlength="30" name="username" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_first_name">First name:</label> <input id="id_first_name" maxlength="30" name="first_name" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_last_name">Last name:</label> <input id="id_last_name" maxlength="30" name="last_name" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_password1">Password:</label> <input id="id_password1" name="password1" type="password" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_password2">Password confirmation:</label> <input id="id_password2" name="password2" type="password" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_num_expediente">Num expediente:</label> <input id="id_num_expediente" name="num_expediente" type="number" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_area">Area:</label> <input id="id_area" name="area" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_fecha_ingreso">Fecha ingreso: MM/DD/YY</label> <input id="id_fecha_ingreso" name="fecha_ingreso" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_fecha_conclusion">Fecha conclusion:MM/DD/YY</label> <input id="id_fecha_conclusion" name="fecha_conclusion" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_evaluacion_completa">Evaluacion completa:</label> <input id="id_evaluacion_completa" name="evaluacion_completa" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_reportes">Reportes:</label> <input id="id_reportes" name="reportes" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_diagnostico">Diagnostico:</label> <input id="id_diagnostico" name="diagnostico" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_fecha_nacimiento">Fecha nacimiento: MM/DD/YY</label> <input id="id_fecha_nacimiento" name="fecha_nacimiento" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_edad_ingreso">Edad ingreso:</label> <input id="id_edad_ingreso" name="edad_ingreso" type="number" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_telefono">Telefono:</label> <input id="id_telefono" name="telefono" type="number" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_email">Email:</label> <input id="id_email" name="email" type="email" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_genero">Genero:</label>
        <select id="id_genero" name="genero">
          <option value="M">Masculino</option>
          <option value="F">Femenino</option>
        </select>
      </div>
      <div class="btn-group  col-xs-8 col-xs-push-2" role="group" aria-label="..." style="padding-left: 0px;padding-right: 0px;">
        <button type="submit" class="btn btn-default btnDef1 col-xs-6">Register</button>
        <button type="reset" class="btn btn-default btnDef2 col-xs-6">Cancel</button>
      </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

Carlos_Home/templates/Carlos_Home/Registro_prof.html
{% extends 'base.html' %}
{% block title %} Registros {% endblock %}
{% block inicio %}
<li class="active"><a href="{% url 'home' %}" data-nav-section="home"><span>Inicio</span></a></li>
{% endblock %}
{% block content %}
<aside class="callout">
  <div class="text-vertical-center">
      <h1 style="color: #fff">Registro Profesionista</h1>
  </div>
</aside>
{% if form.errors %}
<h3>Error</h3>
{{ form.errors }}
{% endif %}
<div class="row">
  <form role = "form" method="POST">
    {% csrf_token %}
    <div class="container text-center" style="padding-top: 15px;">
      <h2>Completa el formulario</h2>
      <hr style="padding-bottom: 15px;" class="small">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="form-group float-label-control">
          <label for="id_username">Username:</label>
          <input id="id_username" maxlength="30" name="username" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_first_name">First name:</label>
        <input id="id_first_name" maxlength="30" name="first_name" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_last_name">Last name:</label>
        <input id="id_last_name" maxlength="30" name="last_name" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_password1">Password:</label>
        <input id="id_password1" name="password1" type="password" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_password2">Password confirmation:</label>
        <input id="id_password2" name="password2" type="password" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_reportes">Reportes:</label>
        <input id="id_reportes" name="reportes" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_horario">Horario:</label>
        <select id="id_horario" name="horario">
          <option value="M">Matutino</option>
          <option value="V">Vespertino</option>
        </select>
      </div>
      <div class="form-group float-label-control">
        <label for="id_telefono">Telefono:</label>
        <input id="id_telefono" name="telefono" type="number" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_curso">Curso:</label>
        <select id="id_curso" name="curso">
          <option value="" selected="selected">Selecciona Curso</option>
          <option value="(u&#39;Clases&#39;,)">(u&#39;Clases&#39;,)</option>
          <option value="(u&#39;Clases&#39;,)">(u&#39;Clases&#39;,)</option>
        </select>
      </div>
      <div class="form-group float-label-control">
        <label for="id_email">Email:</label>
        <input id="id_email" name="email" type="email" />
      </div>
      <div class="btn-group  col-xs-8 col-xs-push-2" role="group" aria-label="..." style="padding-left: 0px;padding-right: 0px;">
        <button type="submit" class="btn btn-default btnDef1 col-xs-6">Register</button>
        <button type="reset" class="btn btn-default btnDef2 col-xs-6">Cancel</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

Carlos_Home/templates/Carlos_Home/contact.html
{% extends 'base.html'%}
{% block title %} Contact {% endblock %}
{% block carrousel %}{% endblock %}
{% block content %}
<aside class="callout" style="background: url(../static/images/contacto.jpg) no-repeat center center scroll;">
  <div class="text-vertical-center">
      <h1 style="color: #fff"> Contactanos</h1>
  </div>
</aside>

<div class="row">
  <form id= "form" role = "form" method="POST" onsubmit="return valida(form)">
    {% csrf_token %}
    <div class="container text-center" style="padding-top: 15px;">
      <h2>Envianos un email con tus datos o preguntas y nos contactaremos contigo</h2>
      <hr style="padding-bottom: 15px;" class="small">
      <div class="col-sm-8 col-sm-offset-2">
      <div class="form-group float-label-control">
        <label for="id_name">Nombre:</label>
        <input id="id_name" name="name" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_emal">Correo:</label>
        <input id="id_emal" name="emal" type="text" />
      </div>
      <div class="form-group float-label-control">
        <label for="id_message">Mensaje:</label>
        <textarea cols="40" id="id_message" name="message" rows="10"> </textarea>
      </div>
      <div class="btn-group  col-xs-8 col-xs-push-2" role="group" aria-label="..." style="padding-left: 0px;padding-right: 0px;">
        <input type="submit" name="name" class= "btn btn-default btnDef1 col-xs-6" value="Enviar Mensaje">
        <input type="reset" name="name" class= "btn btn-default btnDef1 col-xs-6" value="Cancelar">
      </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

Carlos_Home/templates/Carlos_Home/registro.html
{% extends 'base.html' %}
{% block title %}Registro{% endblock %}
{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Register">
		<input type="reset" value="Cancel">
	</form>

{% endblock %}

Carlos_Home/templates/Carlos_Home/reporte_cursos.html
{% extends 'base.html' %}
{% block title %} Reportes {% endblock %}
{% block inicio %}
<li class="active"><a href="{% url 'home' %}" data-nav-section="home"><span>Inicio</span></a></li>
{% endblock %}
{% block content %}
<aside class="callout">
  <div class="text-vertical-center">
      <h1 style="color: #fff">Reporte Cursos</h1>
  </div>
</aside>

<!--{% if user.is_authenticated %}

Binevenido {{ user.username }}<br> -->
		<table class="table table-stripped">
		<th>Numero Curso</th>
		<th>Curso</th>
	{% for item in object_list %}
	<tr>
	<td>{{item.numero_curso}}</td>
	<td>{{item.curso}}</td>
	</tr>
		{% endfor %}
		</table>
  	{% endif %}
{% endblock %}